### ISSUE TITLE
Bilder in Bars werden nicht skaliert

### ISSUE THREAD

**Issue by akamia** [ioBroker/ioBroker.vis-bars#1]
Die Bars können Text und / oder Bilder enthalten. Sowohl SVGs als auch PNGs werden nicht skaliert.
![2015-09-23 19_47_57-iobroker vis](https://cloud.githubusercontent.com/assets/6473286/10053399/1acafeb0-622c-11e5-930f-1ddde07a6236.png)

**Comment by GermanBluefox** [comment]
Bitte testen in der neuen Version.

**Comment by akamia** [comment]
Danke Dir. Leider noch nicht ganz. Der Zoom des Bildes hängt nicht von der Buttomgröße, sondern vom "Bildoffset von Links" ab. Hier drei Bilder: 1. Ohne Icons, 2. Icons mit Offset = 10, 3. Icons mit Offset = 40. Ist unabhängig von png oder svg.

![2015-09-25 19_20_24-iobroker vis](https://cloud.githubusercontent.com/assets/6473286/10107448/55b0900e-63bb-11e5-84d9-2af5a57b4d85.png)

**Comment by GermanBluefox** [comment]
Man kann noch Textabsetzung benutzen
[image: Встроенное изображение 1]

2015-09-25 19:26 GMT+02:00 akamia notifications@github.com:

**Comment by akamia** [comment]
Textabsetzung = 30% bringt bei mir gute Ergebnisse. Ist gelöst.
